export default {
    LOGIN: '/login',
    LOGOUT: '/logout',
    GET_USER_DATA: '/user-data',
    COUNTRIES: '/countries',
    FORM_OPTIONS: '/form-options',
    USERS: '/v1/users',
    CATEGORIES: '/v1/categories',
    ITEMS: '/v1/items',
    PURCHASES: '/v1/purchases',
    STOCKS: '/v1/stocks',
    BRANCHES: '/v1/branches',
    GET_ITEM_BY_BARCODE: '/v1/get-item-by-barcode',
    SALABLE_PRODUCTS: '/v1/salable-products',
    PURCHASABLE_PRODUCTS: '/v1/purchasable-products',
    SHOP_INFO: '/v1/pos/shop-info',
    COMPLETE_SALE_TRANSACTION: '/v1/pos/complete-sale-transaction',
    CANCEL_SALE_TRANSACTION: '/v1/pos/cancel-sale-transaction',
    COMPLETE_PURCHASE_TRANSACTION: '/v1/stores/complete-purchase-transaction',
    CANCEL_PURCHASE_TRANSACTION: '/v1/stores/cancel-purchase-transaction',
    SUPPLIERS: '/v1/suppliers',
}
