export default {
    LOGIN: '/login',
    LOGOUT: '/logout',
    GET_USER_DATA: '/user-data',
    UNITS: '/units',
    ROLES: '/roles',
    USERS: '/users',
    CATEGORIES: '/categories',
    ITEMS: '/items',
    BRANCHES: '/branches',
    FORM_SELECTION_OPTIONS: '/form-selection-options',
    SALABLE_PRODUCTS: '/salable-products',
    PURCHASABLE_PRODUCTS: '/purchasable-products',
    SHOP_INFO: '/shop-info',
}
