export default {
    state: {
        salableProducts: [
            {
                id: 1,
                barcode: '12345678910',
                title: 'Test fgfdfItem 1',
                category: 'Test Category',
                unit: 'kgs',
                price: 6500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 2,
                barcode: '46345678910',
                title: 'Tesertfdft Item 2',
                category: 'Test Category',
                unit: 'kgs',
                price: 1000,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 543,
                barcode: '18345678910',
                title: 'Test rtredfItem 3',
                category: 'Test Category',
                unit: 'kgs',
                price: 2500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 83,
                barcode: '938345678910',
                title: 'Test rewerfItem 3',
                category: 'Test Category',
                unit: 'kgs',
                price: 2500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 13,
                barcode: '898345678910',
                title: 'Test erewrfItem 3',
                category: 'Test Category',
                unit: 'kgs',
                price: 2500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 63,
                barcode: '65345678910',
                title: 'Test sssssItem 3',
                category: 'Test Category',
                unit: 'kgs',
                price: 2500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 53,
                barcode: '903456789104',
                title: 'Test Itemssssss 3',
                category: 'Test Category',
                unit: 'kgs',
                price: 2500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 33,
                barcode: '45345678910',
                title: 'Test Item cccc3',
                category: 'Test Category',
                unit: 'kgs',
                price: 2500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            },
            {
                id: 31,
                barcode: '90345678910',
                title: 'Test Itemffff',
                category: 'Test Category',
                unit: 'kgs',
                price: 2500,
                discount: 0,
                stockQty: 96,
                margin: 15,
                avatar: '',
                type: 'sell',
            }
        ],
        shopInfo: {},
    },
    getters: {
        GET_SALABLE_PRODUCTS: (state) => {
            return state.salableProducts;
        },
        GET_SHOP_INFO: (state) => {
            return state.shopInfo;
        }
    },
    mutations: {},
    actions: {}
}
