export default {
    LOGIN: '/login',
    LOGOUT: '/logout',
    GET_USER_DATA: '/user-data',
    UNITS: '/units',
    ROLES: '/roles',
    USERS: '/users',
    CATEGORIES: '/categories',
    ITEMS: '/items',
    BRANCHES: '/branches',
    FORM_SELECTION_OPTIONS: '/form-selection-options',
    GET_ITEM_BY_BARCODE: '/get-item-by-barcode',
    SALABLE_PRODUCTS: '/salable-products',
    PURCHASABLE_PRODUCTS: '/purchasable-products',
    SHOP_INFO: '/pos/shop-info',
    COMPLETE_SALE_TRANSACTION: '/pos/complete-sale-transaction',
    CANCEL_SALE_TRANSACTION: '/pos/cancel-sale-transaction',
    COMPLETE_PURCHASE_TRANSACTION: '/stores/complete-purchase-transaction',
    CANCEL_PURCHASE_TRANSACTION: '/stores/cancel-purchase-transaction',
    SUPPLIERS: '/suppliers',
    COUNTRIES: '/countries',
}
